version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "${BACKEND_PORT}:3030"
    volumes:
      - ./shared:/shared
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./shared:/shared
    command: npm run dev
    
  #other services

  nginx:
    container_name: 'load-balancer'
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
      - ./infra/nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
  

