version: '3.8'

services:
  api:
    container_name: ${PROJECT_NAME}__api--dev
    build:
      context: ./backend/_api
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:7010"
    volumes:
      - ./backend/_api:/project/_api
      - ./backend/_common:/project/_common
      - ./.env:/app/.env
    working_dir: /project/_api
    command: npm run dev
    env_file:
      - .env

  # app:
  #   container_name: ${PROJECT_NAME}__app--dev
  #   build:
  #     context: ./backend/_dlr
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${BACKEND_PORT}:7010"
  #   volumes:
  #     - ./backend/_dlr:/project/app
  #     - ./backend/_common:/project/_common
  #     - ./.env:/app/.env
  #   working_dir: /project/app
  #   command: npm run dev
  #   env_file:
  #     - .env

  frontend:
    container_name: ${PROJECT_NAME}__frontend--dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:8010"
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env
    environment:
      - PORT=8010
    command: npm run dev
    env_file:
      - .env

  #other services

  nginx:
    container_name: ${PROJECT_NAME}__load-balancer--dev
    image: nginx:stable
    ports:
      - "${PROJECT_PORT}:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
      - ./infra/nginx/logs:/var/log/nginx
      - ./infra/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - frontend
