version: '3.8'

services:
  backend:
    container_name: ${PROJECT_NAME}__backend--dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:7010"
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
      - ./shared:/shared
    command: npm run dev

  frontend:
    container_name: ${PROJECT_NAME}__frontend--dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:8010"
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env
      - ./shared:/shared
    environment:
      - PORT=8010
    command: npm run dev
    
  #other services

  nginx:
    container_name: ${PROJECT_NAME}__load-balancer--dev
    image: nginx:stable
    ports:
      - "${PROJECT_PORT}:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
      - ./infra/nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
  

