FROM node:14 AS build
WORKDIR /app
COPY package*.json /app/
RUN npm i
COPY . .
RUN npm run build

FROM node:14
WORKDIR /app
RUN npm install -g pm2
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

EXPOSE ${BACKEND_PORT}

# Use PM2 to start the application
CMD ["pm2-runtime", "dist/server.js"]